apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-team-a
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-a
    server: https://kubernetes.default.svc
  project: default
  source:
    path: team-a
    repoURL: https://github.com/abinet/argocd-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
